### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by DaddyWarbucks** [jonstuebe/react-router-routes-loader#1]
Hey @jonstuebe,

Thanks for this library. I am interested in using it, but I have a question.

Are you still using this? It looks like it hasn't been updated in 10 months. So I am curious if you found another solution or if you are still using this. If you did find another solution, what is it?

If you are using this, I would like to contribute in adding route params. What can I do to help?

Thanks

**Comment by jonstuebe** [comment]
Yes, I've still been using it. Just haven't had a reason to add additional support. I would love a PR though!

**Comment by DaddyWarbucks** [comment]
Excellent! I am surprised this doesn't have more stars or that there is not some other wildly popular library that does this. I have been mulling ideas around for a while. But, I don't know much about Webpack loaders and when I saw this it made perfect sense. This paired with the new `react-location` router is the routing solution I have been wanting in React for a long time.

I guess the main question that I have before I can make a PR is if you have a preference for the syntax to indicate a param. Next uses brackets and Remix uses dollar signs. Which would you prefer? I think I prefer brackets, but don't have a strong opinion on it.

I am not sure either Next/Remix handle "defined" params either. That is not something I use often, but it's something we should keep in mind I guess. For example, `/items/:tab(active|inactive|all)`. I am not sure how different OS's will handle that...hopefully `[tab(active|inactive|all)].js` is a filename.

```
// Dollar signs
- items
-- index.js
-- $id.js

// Brackets
- items
-- index.js
-- [id].js
```

**Comment by jonstuebe** [comment]
I definitely prefer brackets. Let's def test the OS handling if possible to make sure that it would work on MacOS/Linux/Windows.

**Comment by DaddyWarbucks** [comment]
I have started to work on this and setup a little test app. but I have noticed that changes to files are not reflected unless you restart the app...which is a bummer. Is there anything we can do to solve this?


*Disregard...I must have been doing something wrong...this works as expected*
